[package]
name = "merk"
description = "High-performance Merkle key/value store"
version = "2.0.0"
authors = ["Turbofish <team@turbofish.org>"]
edition = "2018"
license = "Apache-2.0"

[workspace]

[dependencies]
thiserror= "1.0.58"
serde = { version = "1.0", features = ["derive"] }
# Use RISC0's accelerated SHA256 when compiled for guest.  To compile for RISC0 use this crate with default-features=false
sha2 = { git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }

[dependencies.ed]
version = "0.2"

[dependencies.rand]
version = "0.8.5"
features = ["small_rng"]
optional = true

[features]
bench = ["dep:rand"]
box = []

[dev-dependencies.rand]
version = "0.8.5"
features = ["small_rng"]

[dev-dependencies.criterion]
version = "0.5"

[dev-dependencies.serde_json]
version = "1.0"

[[bench]]
name = "ops"
harness = false
required-features = ["bench"]

[[bench]]
name = "tracer"
harness = false
required-features = ["bench"]
